version: 2
updates:
- package-ecosystem: "docker"
  directory: "/"
  commit-message:
    prefix: "docker"
  labels: [ 'docker' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    docker-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: "actions"
  labels: [ 'github-actions' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    actions-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
- package-ecosystem: "pip"
  directory: "/"
  commit-message:
    prefix: "pip"
    prefix-development: "pip-dev"
  labels: [ 'dependencies' ]
  assignees:
  - "Harvester57"
  schedule:
    interval: "cron"
    cronjob: "0 7 * * *"
    timezone: "Europe/Paris"
  groups:
    pip-dev-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
      dependency-type: development
    pip-prod-dependencies:
      applies-to: version-updates
      patterns:
      - "*"
      dependency-type: production
  allow:
  - dependency-type: all
