name: 'Build and Publish Release to DockerHub'

on:
  release:
    types: [created]

jobs:
    buildx:
        runs-on: ubuntu-latest
        steps:
        -
            name: Checkout
            uses: actions/checkout@v4
        - 
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
        -   
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
        -
            name: Login to DockerHub
            uses: docker/login-action@v3 
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}
        -
            name: Get Release Tag
            id: release
            run: |
              DOCKER_IMAGE=opensecurity/njsscan
              if [[ $GITHUB_REF == refs/tags/* ]]; then
                VERSION=${GITHUB_REF#refs/tags/}
                TAG="${DOCKER_IMAGE}:${VERSION}"
              fi
              echo ::set-output name=tag::${TAG}
        -
            name: Build and push release
            id: docker_build
            uses: docker/build-push-action@v6
            with:
                push: true
                context: .
                platforms: linux/amd64,linux/arm64
                tags: ${{ steps.release.outputs.tag }}
